language: node_js
node_js:
  - "node"
addons:
  chrome: stable
  firefox: latest
sudo: required
cache: yarn
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - yarn build
  - yarn test